### ISSUE TITLE
Uncaught Exception Error when trying to create a new Library

### ISSUE THREAD

**Issue by aharonach** [atrocore/atrodam#108]
Hi,
When trying to create a new Library on the system, this error is thrown:
`Uncaught Exception Error: "Class "Dam\Listeners\AbstractListener" not found" at /public_html/vendor/atrocore/dam/app/Repositories/Library.php line 107 {"exception":"[object] (Error(code: 0): Class \"Dam\\Listeners\\AbstractListener\" not found at /public_html/vendor/atrocore/dam/app/Repositories/Library.php:107)"} []`

I believe that in `dam/app/Repositories/Library.php`, line 34 should be replaced with `use Dam\Listeners\Metadata;`
but in Metadata.php there isn't a const named CODE_PATTERN

**Comment by rratsun** [comment]
Fixed at DAM 1.5.6
