### ISSUE TITLE
Asset Import Failure when same file imported with different name

### ISSUE THREAD

**Issue by paultvis** [atrocore/atrodam#110]
We have hit an issue importing images from a supplier feed. When creating the assets, the import job count matches the import file (397 created) but when you look at the assets created, there are only 311. There are no duplicates in the file there are no errors reported either in the UI or in logs.

**Comment by paultvis** [comment]
I have been doing some more investigation on this and the behaviour is not as simple as I described above. I queried the db to get missing assets in the feed. It gave me 640 assets to add. I added those, and opening the results gave 367. When I requeried the data sets again, I expected to see 273 however I got the same 640 rows returned. 

So i delved into a single asset, screengrabba_01.jpg in my feed. There was no asset called that in the list of created assets, but there was screengrabba_01_1.jpg. I assume that the import has decided that that is the same image so has not created again. 

Regardless of whether it is the same image or not, it has not not created the asset which needs to be added to the product.

**Comment by paultvis** [comment]
Can I ask if anyone has looked at this issue? This is now impacting us heavily as we are unable to add new products for at least one particular supplier. As an example, yesterday I took a different approach to extracting images in the feed and it created an import file with 830 images. On import, the job appeared to create 796, however I suspect most of those were not created, it just returned similar or the same file with a different name. When I came to match those up with products (still using the same original file names from the supplier feed), the import file had 430 products to be updated. On running the import, the job was only able to match 19 products. This issue is seriously limiting us as atro simply is not doing what we are asking it to do.

**Comment by paultvis** [comment]
Hi,

Sorry, I meant to respond to this. That did work, however I would say that I did look for some kind of setting for that, but only looked in the DAM administration module. Either a reference in the documentation would be useful or move the field to the DAM settings.

Thanks

Paul

**Comment by rratsun** [comment]
@paultvis Field 'Asset Duplicates' has been moved into DAM settings in DAM 1.5.16
