### ISSUE TITLE
Can't save unchecked checkbox

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrodam#113]
In my instances and the extended demo[1] I can't save the unchecked status of the "Private" field.
Screencast here: https://github.com/atrocore/atrodam/assets/1337223/3446d05d-80c2-4997-bec3-3a4cd72a1f25

[1] demo.atropim.com is empty, so I couldn't test

**Comment by rratsun** [comment]
Fixed at DAM 1.5.14
