### ISSUE TITLE
Inconsistent behavior for filenames with dots

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrodam#61]
1. have an asset with a dot in the filename
2. Edit the asset entry (changing the description or something like that)
3. Entry can't be saved
4. Removing dot from filename works

https://user-images.githubusercontent.com/1337223/173301005-95ec51d7-5925-43da-a186-a13cb1fec895.mp4

**Comment by atrolex** [comment]
This is definitely a bug, we will fix it soon.
