### ISSUE TITLE
Missing `asset.private` field

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atrodam#75]
Not sure if it is my problem, but since I was able to reproduce it in the demo, I'll post it here:

I set an asset to `private`:

![image](https://user-images.githubusercontent.com/1337223/187874660-617264c3-9e6e-46ce-ae5c-8e69bb0ac2d9.png)

When I tried to filter for private assets I got an Error 500 and this in the logs.
```
[2022-09-01T06:25:18.501115+00:00] Log.ERROR: API [GET]:/api/v1/:controller, Params:Array (     [controller] => Asset ) , InputData:  - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'asset.private' in 'where clause' [] []
[2022-09-01T06:25:18.533951+00:00] Log.ERROR: Display Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'asset.private' in 'where clause', Code: 42S22 URL: /api/v1/Asset?select=preview%2Cname%2CproductsIds%2CproductsNames%2Ctype&maxSize=50&offset=0&sortBy=createdAt&asc=false&where%5B0%5D%5Btype%5D=isFalse&where%5B0%5D%5Battribute%5D=private [] []
```

Checking the DB the field is indeed missing.
The only reference in the DB Code I was able to find here: https://github.com/atrocore/atrodam/blob/45a5e375857621dbd64e6666921bc3fce2d4ee36/app/Migrations/V1Dot1Dot0.php#L62 - since it's a CHANGE it must have existed before?

I tested it in the demo instance and the filter call fails as well

![image](https://user-images.githubusercontent.com/1337223/187874178-1ac628cf-a51e-420a-ad05-1f376f5657ea.png)

**Comment by rratsun** [comment]
Hello,

Field 'private' is virtual, so you cannot sort or filtering via this field.
Please, use this boolean filter instead (DAM 1.4.3):
![image](https://user-images.githubusercontent.com/33658723/189366549-dfcf0ad9-83c1-48e2-8cc3-d40982d40fa2.png)

**Comment by marcus-at-localhost** [comment]
perfect! thank you!

**Comment by marcus-at-localhost** [comment]
Would this call work as well `/Category/:entityId/assets?where[0][type]=bool&where[0][attribute]=onlyPublic`?

**Comment by rratsun** [comment]
No. You should use a subquery functionality.

```/api/v1/Category?select=name,code,isActive&maxSize=1&offset=0&sortBy=createdAt&asc=false&where[0][type]=linkedWith&where[0][attribute]=assets&where[0][subQuery][0][type]=bool&where[0][subQuery][0][value][]=onlyPublic&where[1][type]=equals&where[1][attribute]=id&where[1][value]=6303287067cff0815```

**Comment by marcus-at-localhost** [comment]
Oh wow, I didn't know about the subqueries. Will investigate! Thank you!
