### ISSUE TITLE
Delete Import Deletes all Assets

### ISSUE THREAD

**Issue by paultvis** [atrocore/atrodam#94]
Passing a file with asset names to a delete import deletes all assets, not just those listed in the file.

Following issues importing assets, we attempted to delete assets already referenced in the file. The import file contained around 600 entries, which we knew about 100 existed. The import job was stopped after it had deleted around 3k assets. A second attempt using the same file was stopped after the number of assets deleted reached just under 1k.

**Comment by paultvis** [comment]
This appears to be a wider issue than just on assets. We tried to remove some attribute values from products using delete attribute values import. The ID of the attribute values was used as the identifier. The import (delete) file had 1635 entries. The job was stopped when it reached 1900 items deleted. Checking in the database the entries that were deleted were not in the file, so it appears that it was attempting to delete all entries. 

It appears that running any delete import will attempt to delete all entries of the entity type being removed

**Comment by paultvis** [comment]
Hi, thanks. If that is what it is designed to do then it is correct. It is a strange way of running the import though, and very non standard I would say. If I have 100k products in my catalogue and I know 10 need to be deleted, I need to provide a file with the remaining 99990 IDs. Not intuitive at all and being non standard behaviour does make it dangerous.

**Comment by rratsun** [comment]
I agree with you, and we have internal issue for change behavior in this functionality. We have many internal issues :) Doing them as quick as we can.
