### ISSUE TITLE
Non funziona la ricerca per tag

### ISSUE THREAD

**Issue by Lara81** [atrocore/atrodam#95]
Abbiamo riscontrato che non funziona la ricerca per tag da un paio di giorni, allego immagine con esempio: a sinistra notate che la cartella Mare ha delle foto con il tag Pineto, mentre nella schermata a destra la ricerca per tag Pineto risulta vuota 

![esempio-errore](https://user-images.githubusercontent.com/60141835/217580085-a2ea562d-35b5-4789-bca5-1b04fa41e40a.jpg)

**Comment by asapko** [comment]
Hello! We have tested this on our test platforms and could search products by tags. Could you give us more info (or may be in an issue of an older version)?
